### ISSUE TITLE
Hello, I have a question, in the Branch.cs

### ISSUE THREAD

**Issue by fygzg** [theraot/Theraot.Collections.ThreadSafe#1]
![image](https://user-images.githubusercontent.com/6488196/35904492-452fcbba-0c1e-11e8-912b-08a6b3b404ff.png)

**Comment by theraot** [comment]
For abstract, it is wrong.

This is the fixed version:
https://github.com/theraot/Theraot/blob/6c2c70ebaab512cfcb087c54013daee578a63ce8/Core/Theraot/Collections/ThreadSafe/Branch.cs#L328

---

First off, I no longer use the version from this repository. Have a look at
https://github.com/theraot/Theraot/tree/master/Core/Theraot/Collections/ThreadSafe

I started importing code from this repository (good old copy and paste) in
the commit
https://github.com/theraot/Theraot/commit/a2729e02e9cd8c5361681e0e9a8f0554a4820284#diff-e2907db33baa301a61ef20dbd7e6d114

The history of those files before that point is in this repository.

In fact, the current version does no longer have Mapper and Branch. If you
want to look for their replacement, they are Bucket and BucketCore.

2018-02-07 2:49 GMT-05:00 fygzg <notifications@github.com>:

**Comment by fygzg** [comment]
Thank you for your answer!
